### ISSUE TITLE
If timeout occurs during a subscription request, user will receive a "Failed to add subscription" error message

### ISSUE THREAD

**Issue by randywsandberg** [beAutomated/benchmark-email-lite#10]
Setup:
- Go to http://dev-benchmark-email-lite.pantheonsite.io/wp-admin/, log in as an admin, go to BenchmarkEmail > Settings > Diagnostics and set Connection Timeout to 1 just to make sure it really does timeout.

Steps to reproduce:
1. Go to http://dev-benchmark-email-lite.pantheonsite.io/
2. For First Name, enter Jerry
3. For Last Name, enter Ryan
4. For Email, enter an address you have access and that hasn’t yet been added to the contact
5. Click Subscribe

Result:
System reported, “Failed to add subscription. Please try again later.” See Screenshot 1. As predicted, there was a Connection Timeout on the site (see Screenshot 2). And yet, during the timeout the user still received a “Please confirm your subscription to our mailing list” email.

Expected result:
System to timeout and issue a “Successfully queued subscription.” message to the user. Which, by the way, does occur if the user tries to subscribe again. See Screenshot 3.

Workaround:
No

Reproducible?
Always

Occurs:
- Mac Safari 9.1.1 + BMEL 2.6 [536c3f2]
- Mac Chrome 51.0.2704.84 (64-bit) + BMEL 2.6 [536c3f2]

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/15979135/ff396066-2f16-11e6-8c7d-f3e3bb7ad8c3.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/15979138/ff5445d4-2f16-11e6-987f-ec658a4b9970.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/19829655/15979139/ff54d986-2f16-11e6-8c30-e8d78b0cb0b9.png)

**Comment by seanconklin** [comment]
The primary issue here is BME is returning an empty response for this particular API key and/or Contact List. It still subscribed the user, as reported, so it did not return an error, just provided no feedback to our plugin and left it hanging for a response that eventually defaulted in error.

The secondary issue here is that the queue is not enabled until the first error, so that triggering error itself  being a subscription request does not itself queue. We do perform communications for `listGet` and `listGetContacts` successfully immediately before requesting the failing `listAddContactsOptin` communication. So that is why we have not seen this problem before, since a server down issue would generally be discovered before that third request in the submission sequence is made.

**Comment by randywsandberg** [comment]
Could not reproduce using Win Chrome 51.0.2704.84 m (64-bit) + BMEL 2.6 [68bcb3a]. See screenshots. Closing as fixed.

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/16063875/4d5a8a80-3251-11e6-86c6-f873b3bd270f.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/16063874/4d57d9b6-3251-11e6-9349-97a294d080c7.PNG)
![screenshot 3](https://cloud.githubusercontent.com/assets/19829655/16063873/4d56f32a-3251-11e6-96f8-1d89080953fb.PNG)
